### PR TITLE
Add support for factorissimo-2-notnotmelon fork

### PR DESCRIPTION
**Pull request by pixelcort**
https://mods.factorio.com/mod/Factorissimo2-Playthrough/discussion/62f0364dafdba54bfd8860ff

### CODE REVIEW

**Comment by oof2win2** [comment]
This PR replaces the suport for factorissimo-2 with factorissimo-2-notnotmelon, which means that existing users would not be able to use factorissimo-2. In my opinion, support for both should be kept, as not everyone wants to switch to the latter notnotmelon fork (f.e. they don't know about it).

To be honest, I am pretty sure that your code changes would not edit. Only from the README of the notnotmelon fork, I see that there will 100% be issues with pipes at least (which should be an easy toggle, just check which of the two mods is enabled).

I have commented on the rest of the situation on the Factorio mod forums thread.

**Comment by pixelcort** [comment]
Got it, thanks! Yep, I see the pipe issue too.

Regarding support for both mods; I'm concerned as it would mean marking both as optional, but that would make the mod not automatically enable one of them when it was enabled. I don't think we can specify "required X or Y mod" in the config, and one of the benefits of having a required mod is that when the mod is enabled the dependencies are also automatically enabled at the same time.

Assuming I'm able to get the pipe stuff and any other issues resolved, would you be okay if I forked this mod and re-submitted it to the mod portal as a fork? It looks like it's set to an MIT license according to the portal, so I would follow that license as well in the fork and give credit and everything. Of course, please feel free to say no if you prefer me or someone else to resubmit another PR with support for both dependencies.

Let me close this PR for now as it won't work as-is and I can't guarantee if and when I can fix it.

**Comment by oof2win2** [comment]
> Regarding support for both mods; I'm concerned as it would mean marking both as optional, but that would make the mod not automatically enable one of them when it was enabled. I don't think we can specify "required X or Y mod" in the config, and one of the benefits of having a required mod is that when the mod is enabled the dependencies are also automatically enabled at the same time.

Yeah, not sure if that can be resolved at all with the current Factorio options for dependencies.

Regarding resubmitting this mod, go ahead. It's open source, and if you'd credit me it would be nice, but I don't mind not being there. If anything, just reach for help 👍

**Comment by ZLioxygon** [comment]
notnotmelon surfaces naming:
in "scripts/factoryies.lua"
changes all
"Factory floor 1"
to
"factory-floor-1"
(6 times)

**Pull request closed without merging**
